/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelDominio.Cinema;
import modelDominio.Filme;
import view_util.ProgramaComboBox;


/**
 *
 * @author Usuário
 */
public class TelaHome extends javax.swing.JFrame {

private Cinema cinemaLogado;
    
private ArrayList<Filme> listaFilmes;

    public TelaHome(Cinema cinemaLogado) {
    this.cinemaLogado = cinemaLogado;
     initComponents();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jBDadosCinema = new javax.swing.JButton();
        jBAdicionarFilme = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLMeusFilmes = new javax.swing.JLabel();
        jCBFilmes = new javax.swing.JComboBox<>();
        jBAtualizar = new javax.swing.JButton();
        jBHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jBDadosCinema.setText("Dados do cinema");
        jBDadosCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDadosCinemaActionPerformed(evt);
            }
        });

        jBAdicionarFilme.setText("Adicionar filme");
        jBAdicionarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarFilmeActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLMeusFilmes.setBackground(new java.awt.Color(51, 51, 51));
        jLMeusFilmes.setForeground(new java.awt.Color(51, 51, 51));
        jLMeusFilmes.setText("Meus filmes:");

        jCBFilmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFilmesActionPerformed(evt);
            }
        });

        jBAtualizar.setText("Atualizar lista");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLMeusFilmes)
                    .addComponent(jCBFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAtualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLMeusFilmes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBAtualizar)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jBHome.setText("Home");
        jBHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBDadosCinema, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jBAdicionarFilme, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jBSair, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jBHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(560, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jBHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDadosCinema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAdicionarFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSair)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBDadosCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDadosCinemaActionPerformed
        TelaCadastro dadosCinema = new TelaCadastro();
        dadosCinema.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBDadosCinemaActionPerformed

    private void jBAdicionarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarFilmeActionPerformed
        System.out.println("CINEMA LOGADO: "+ cinemaLogado.getIdCinema());
        TelaCadastrarFilme tcf = new TelaCadastrarFilme(cinemaLogado); // passa a Home
        tcf.setLocationRelativeTo(this);
        tcf.setVisible(true);
    }//GEN-LAST:event_jBAdicionarFilmeActionPerformed

    private void jBHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHomeActionPerformed
   
    }//GEN-LAST:event_jBHomeActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
       int resposta = JOptionPane.showConfirmDialog(
            this,
            "Tem certeza que deseja fechar?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION
    );

    if (resposta == JOptionPane.YES_OPTION) {
        dispose();
    }
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        // chama a classe utilitária para recarregar a ComboBox
        listaFilmes = view_util.ProgramaComboBox.carregarFilmesComboBox(jCBFilmes);
        JOptionPane.showMessageDialog(this, "Lista de filmes atualizada!");

    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jCBFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFilmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBFilmesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionarFilme;
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBDadosCinema;
    private javax.swing.JButton jBHome;
    private javax.swing.JButton jBSair;
    private javax.swing.JComboBox<String> jCBFilmes;
    private javax.swing.JLabel jLMeusFilmes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    
}
