/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.security.MessageDigest;
import javax.swing.JOptionPane;
import modelDominio.Cinema;
//import view_util.SegurancaUtil;

/**
 *
 * @author victo
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    private Cinema cinema;

    public TelaCadastro() {
        initComponents();
    }

    public void setCinema(Cinema c) {
        jTxtNomeCinema.setText(c.getNomeCinema());
        jTxtEndereco.setText(c.getEndereco());
        jTxtCnpj.setText(c.getCnpj());
        jPFSenha.setText(c.getSenha());

        this.cinema = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNome_cinema = new javax.swing.JLabel();
        jLEndereco = new javax.swing.JLabel();
        jLCNPJ = new javax.swing.JLabel();
        jLSenha = new javax.swing.JLabel();
        jTxtNomeCinema = new javax.swing.JTextField();
        jTxtEndereco = new javax.swing.JTextField();
        jTxtCnpj = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jPFSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setBackground(new java.awt.Color(255, 255, 255));

        jLNome_cinema.setText("Nome do Cinema");

        jLEndereco.setText("Endereço");

        jLCNPJ.setText("CNPJ");

        jLSenha.setText("Digite sua Senha");

        jTxtNomeCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeCinemaActionPerformed(evt);
            }
        });

        jBCadastrar.setBackground(new java.awt.Color(0, 102, 153));
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLNome_cinema)
                    .addComponent(jLCNPJ)
                    .addComponent(jLSenha)
                    .addComponent(jLEndereco)
                    .addComponent(jTxtNomeCinema, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jTxtEndereco)
                    .addComponent(jTxtCnpj)
                    .addComponent(jPFSenha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLNome_cinema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeCinema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLEndereco)
                .addGap(12, 12, 12)
                .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLSenha)
                .addGap(7, 7, 7)
                .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNomeCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeCinemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeCinemaActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed

        if (jTxtNomeCinema.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o nome do cinema.");
            jTxtNomeCinema.requestFocus();
            return;
        }

        else if (jTxtEndereco.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o endereço.");
            jTxtEndereco.requestFocus();
            return;
        }

        else if (jTxtCnpj.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o CNPJ.");
            jTxtCnpj.requestFocus();
            return;
        }

        else if (jPFSenha.equals("")) {
            JOptionPane.showMessageDialog(this, "Digite uma senha.");
            jPFSenha.requestFocus();
            return;
        }else{
            
        
            
            
        //Inserir ou Editar
        boolean result = false;
        try{
            // Pega a senha digitada no campo de senha como um array de caracteres.
            char[] senhaC = jPFSenha.getPassword();
            // Converte o array de caracteres em uma String normal.
            String senha = new String(senhaC);
            // Cria um objeto que gera o hash usando o algoritmo SHA-256.
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            // Converte a senha para bytes e gera o hash (pra ficar seguro).
            byte messageDigest[ ] = md.digest(senha.getBytes("UTF-8"));
            // Cria um StringBuilder para montar o hash em formato de texto.
            StringBuilder sb = new StringBuilder();
            // Converte cada byte do hash para texto hexadecimal e adiciona no StringBuilder.
            for(byte b: messageDigest){
            sb.append(String.format("%02x",0xFF & b));
            }
            // Transforma tudo em uma String final: essa é a senha criptografada.
            String senhaCripto = sb.toString();
        if (cinema == null) {
            
            // Cadastro novo
            Cinema c = new Cinema( jTxtNomeCinema.getText(), jTxtEndereco.getText(), jTxtCnpj.getText(),senhaCripto);
            result = Principal.ccont.cinemaInserir(c);
        } else {
           // Editando cinema existente
          Cinema editado = new Cinema(cinema.getIdCinema(),jTxtNomeCinema.getText(), jTxtEndereco.getText(), jTxtCnpj.getText(), senhaCripto);
          result = Principal.ccont.cinemaEditar(editado);
              
        }

        //Resultado
        if (result) {
            JOptionPane.showMessageDialog(this, "Cinema salvo com sucesso!");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar cinema.");
        }
            

        }catch (Exception e) {
            e.printStackTrace();
             JOptionPane.showMessageDialog(this, "Algo deu errado!!");
        }
}
    }//GEN-LAST:event_jBCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JLabel jLCNPJ;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLNome_cinema;
    private javax.swing.JLabel jLSenha;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JTextField jTxtCnpj;
    private javax.swing.JTextField jTxtEndereco;
    private javax.swing.JTextField jTxtNomeCinema;
    // End of variables declaration//GEN-END:variables
}
