/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import modelDominio.Cinema;
import modelDominio.Filme;
/**
 *
 * @author Usuário
 */
public class TelaCadastrarFilme extends javax.swing.JFrame {

    private Filme filme;
    private Cinema cinemaLogado;
    
    public TelaCadastrarFilme(Cinema cinemaLogado) {
        this.cinemaLogado = cinemaLogado;
        initComponents();
    }

    public void setFilme(Filme f) {
  

        jTxtTitulo.setText(f.getTitulo());
        jTADescricao.setText(f.getDescricao());
        jTxtClass.setText(f.getClassificacao());
        jTxtNumeroPoltrona.setText(f.getNumeroPoltronas());
        jTxtPreco.setValue(f.getPreco());
        jTxtDataInicio.setText(f.getDataInicio());
        jTxtDataTermino.setText(f.getDataTermino());
        this.filme = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLDataInicio = new javax.swing.JLabel();
        jLDataTermino = new javax.swing.JLabel();
        jLClassificacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescricao = new javax.swing.JTextArea();
        jLNumeroDePoltronas = new javax.swing.JLabel();
        jLDescricao = new javax.swing.JLabel();
        jBCadastrarFilme = new javax.swing.JButton();
        jTxtClass = new javax.swing.JTextField();
        jTxtNumeroPoltrona = new javax.swing.JTextField();
        jTxtTitulo = new javax.swing.JTextField();
        jTxtDataInicio = new javax.swing.JTextField();
        jTxtDataTermino = new javax.swing.JTextField();
        jLPreco = new javax.swing.JLabel();
        jLTitulo = new javax.swing.JLabel();
        jTxtPreco = new javax.swing.JFormattedTextField();
        jBHome = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLDataInicio.setForeground(new java.awt.Color(51, 51, 51));
        jLDataInicio.setText("Data de inicio da seção:");

        jLDataTermino.setForeground(new java.awt.Color(51, 51, 51));
        jLDataTermino.setText("Data de termino da seção:");

        jLClassificacao.setForeground(new java.awt.Color(51, 51, 51));
        jLClassificacao.setText("Classificação indicativa:");

        jTADescricao.setColumns(20);
        jTADescricao.setRows(5);
        jScrollPane1.setViewportView(jTADescricao);

        jLNumeroDePoltronas.setForeground(new java.awt.Color(51, 51, 51));
        jLNumeroDePoltronas.setText("Numero de poltronas:");

        jLDescricao.setForeground(new java.awt.Color(51, 51, 51));
        jLDescricao.setText("Descrição:");

        jBCadastrarFilme.setText("Cadastrar");
        jBCadastrarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarFilmeActionPerformed(evt);
            }
        });

        jTxtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTituloActionPerformed(evt);
            }
        });

        jTxtDataTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDataTerminoActionPerformed(evt);
            }
        });

        jLPreco.setForeground(new java.awt.Color(51, 51, 51));
        jLPreco.setText("Preço:");

        jLTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLTitulo.setText("Titulo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLNumeroDePoltronas)
                    .addComponent(jLClassificacao)
                    .addComponent(jLDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNumeroPoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLPreco)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLDataInicio)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLDataTermino)
                        .addGap(14, 14, 14)
                        .addComponent(jTxtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBCadastrarFilme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLClassificacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNumeroDePoltronas)
                            .addComponent(jTxtNumeroPoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLDescricao)
                                .addGap(176, 176, 176))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBCadastrarFilme)
                                    .addComponent(jScrollPane1))
                                .addGap(28, 28, 28))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPreco)
                            .addComponent(jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDataInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDataTermino))
                        .addGap(28, 28, 28))))
        );

        jBHome.setText("Home");
        jBHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBHome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jBHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarFilmeActionPerformed
        // convertendo o valor
        float valores;
        try {
            valores = Float.parseFloat(jTxtPreco.getText().replace(",",","));
        } catch (Exception e) {
            valores = 0;
        }
        if (jTxtClass.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o Titulo!");
            jTxtClass.requestFocus();
        }
        if (jTxtNumeroPoltrona.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha a Descrição!");
            jTxtNumeroPoltrona.requestFocus();
        }
        if (jTADescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha a Descrição!");
            jTADescricao.requestFocus();
        }
        if (valores == 0) {
            JOptionPane.showMessageDialog(this, "Preencha um preço!");
            jTxtPreco.requestFocus();
        }
        if (jTxtTitulo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha a Descrição!");
            jTxtTitulo.requestFocus();
        }
        if (jTxtDataInicio.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha a Descrição!");
            jTxtDataInicio.requestFocus();
        }
        if (jTxtDataTermino.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha a Descrição!");
            jTxtDataTermino.requestFocus();
        }
       
        //Inserir ou Editar
        boolean result = false;

        if (filme == null) {
          
            // cadastrar
            Filme editando = new Filme(cinemaLogado.getIdCinema(),jTxtTitulo.getText(), jTADescricao.getText(), jTxtClass.getText(), jTxtNumeroPoltrona.getText(), valores, jTxtDataInicio.getText(), jTxtDataTermino.getText());
            result = Principal.ccont.filmeInserir(editando);
        } else {
            // editar
            Filme novoFilme = new Filme(filme.getIdFilme(),cinemaLogado.getIdCinema(),jTxtTitulo.getText(), jTADescricao.getText(), jTxtClass.getText(), jTxtNumeroPoltrona.getText(), valores, jTxtDataInicio.getText(), jTxtDataTermino.getText());
            result = Principal.ccont.FilmeEditar(novoFilme);
        }
        //Resultado
        if (result) {
            JOptionPane.showMessageDialog(this, "Cinema salvo com sucesso!");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar cinema.");
        }
        

    }//GEN-LAST:event_jBCadastrarFilmeActionPerformed

    private void jTxtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTituloActionPerformed

    private void jTxtDataTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDataTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDataTerminoActionPerformed

    private void jBHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHomeActionPerformed

        dispose();
    }//GEN-LAST:event_jBHomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarFilme;
    private javax.swing.JButton jBHome;
    private javax.swing.JLabel jLClassificacao;
    private javax.swing.JLabel jLDataInicio;
    private javax.swing.JLabel jLDataTermino;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLNumeroDePoltronas;
    private javax.swing.JLabel jLPreco;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTADescricao;
    private javax.swing.JTextField jTxtClass;
    private javax.swing.JTextField jTxtDataInicio;
    private javax.swing.JTextField jTxtDataTermino;
    private javax.swing.JTextField jTxtNumeroPoltrona;
    private javax.swing.JFormattedTextField jTxtPreco;
    private javax.swing.JTextField jTxtTitulo;
    // End of variables declaration//GEN-END:variables
}
